//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTrackingTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminTable
    {
        public int Id { get; set; }
        public string aName { get; set; }
        public string aPassword { get; set; }
    }
}
